steps:
  # build env file with secrets
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: '/bin/bash'
    args: ['-c', 'echo "REACT_APP_FIREBASE_APIKEY=" > .env']
    dir: 'client/web'
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: '/bin/bash'
    args: ['-c', 'secrets versions access latest --secret=REACT_APP_FIREBASE_APIKEY >> .env']
    dir: 'client/web'
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: '/bin/bash'
    args: ['-c', 'echo "REACT_APP_FIREBASE_APPID=" >> .env']
    dir: 'client/web'
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: '/bin/bash'
    args: ['-c', 'secrets versions access latest --secret=REACT_APP_FIREBASE_APPID >> .env']
    dir: 'client/web'
  # install front end dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'client/web'
  # create front end prod build
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'client/web'
  # deploy front end to Firebase
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['deploy', '--project', '$PROJECT_ID', '--only=hosting']
    dir: 'client/web'